### ISSUE TITLE
Incompatible with protobuf 34.0

### ISSUE THREAD

**Issue by dbermond** [abique/hefur#53]
It fails to build with protobuf 34.1 with the following error:

```
/build/hefur/src/hefur/mimosa/mimosa/rpc/gen/protoc-gen-mimosa.cc:9:10: fatal error: google/protobuf/compiler/cpp/generator.h: No such file or directory
    9 | #include <google/protobuf/compiler/cpp/generator.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [mimosa/mimosa/rpc/gen/CMakeFiles/protoc-gen-mimosa.dir/build.make:79: mimosa/mimosa/rpc/gen/CMakeFiles/protoc-gen-mimosa.dir/protoc-gen-mimosa.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1772: mimosa/mimosa/rpc/gen/CMakeFiles/protoc-gen-mimosa.dir/all] Error 2
```

This is exactly the same problem discussed in #52. Upstream protobuf [restored](https://github.com/protocolbuffers/protobuf/commit/0b1a9c99c4238fc45cbc685dffc89ea8b69b6e5a) the private headers that were previously [removed](https://github.com/protocolbuffers/protobuf/commit/b4b93b36245a88a3efa19261638f5da61a9be44f), but postponed the removal to a later version, giving time for developers to adapt.

It looks like the time has come for the definitive removal, as the private headers were permanently removed as a breaking-change in protobuf 34.0: https://github.com/protocolbuffers/protobuf/commit/3a2af3510f0d454dbe3e4dc281674b61c4d20b9e

It is possible to make hefur to build with a workaround, by the using the protobuf sources and adding the private headers location to the include path in CXXFLAGS (as shown [here](https://github.com/abique/hefur/issues/52#issuecomment-2721595402)), but this is far from optimal at the packing level, needing a change to keep going with protubuf 34.0 and later.
