### ISSUE TITLE
fail build with GCC 6.1.1

### ISSUE THREAD

**Issue by sl1pkn07** [abique/hefur#20]
i'm not sure if is issue of mimosa, but

```
[  3%] Building CXX object hefur/CMakeFiles/hefur-proto.dir/hefur.pb.cc.o
In file included from /tmp/makepkg/hefur-git/src/hefur/mimosa/mimosa/rpc/channel.hh:8:0,
                 from /tmp/makepkg/hefur-git/src/hefur/hefur/hefur.pb.h:37,
                 from /tmp/makepkg/hefur-git/src/hefur/hefur/hefur.pb.cc:5:
/tmp/makepkg/hefur-git/src/hefur/mimosa/mimosa/rpc/../channel.hh: In member function 'void mimosa::Channel<T, QueueType>::maxSize() const':
/tmp/makepkg/hefur-git/src/hefur/mimosa/mimosa/rpc/../channel.hh:46:14: error: return-statement with a value, in function returning 'void' [-fpermissive]
       return max_size_;
              ^~~~~~~~~
make[2]: *** [hefur/CMakeFiles/hefur-proto.dir/build.make:71: hefur/CMakeFiles/hefur-proto.dir/hefur.pb.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2348: hefur/CMakeFiles/hefur-proto.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

greetings

**Comment by abique** [comment]
I forgot to push.... sorry :)

**Comment by sl1pkn07** [comment]
now build OK, but  when run manual Makefile:

```
xsltproc -o manual.html /usr/share/xml/docbook//html/docbook.xsl manual.xml
warning: failed to load external entity "/usr/share/xml/docbook/xsl-stylesheets-1.78.1/html/docbook.xsl"
cannot parse /usr/share/xml/docbook/xsl-stylesheets-1.78.1/html/docbook.xsl
```

i'm not sure if change 'xsl-stylesheets-1.78.1' to 'xsl-stylesheets-*' is a god fix

greetings

**Comment by abique** [comment]
But that one will fail if there are two versions installed, I don't know what's best here.
